### ISSUE TITLE
Tasks stalled on initial install

### ISSUE THREAD

**Issue by OurWebTeam** [opendevshop/devshop#139] opened 2016-07-18 16:12 UTC
So far this was really easy thank you!

But the install doesn't look complete or something has stalled perhaps.

What should be done about this.

![whatsgoingon](https://cloud.githubusercontent.com/assets/20520869/16921775/e493acf2-4ce0-11e6-977c-c405d531b086.png)

**Comment by jonpugh** [comment] 2016-07-18 16:14
You can cancel the task by clicking "View"... There should be a "Cancel" button on that page.

If supervisor is running the next tasks should kick off.

If you don't mind, I'm going to edit your issue to be more specific about this particular bug.

Try the task cancelling and let me know!

**Comment by OurWebTeam** [comment] 2016-07-18 16:28
Sure edit the bug please.

The cancel seems to make that task now green and then the next one is waiting.

Supervisor is running as far as can see.

```shell
root@webteam:/home/user# supervisorctl status
hosting_queue_runner             RUNNING    pid 1531, uptime 0:39:12
```

**Comment by OurWebTeam** [comment] 2016-07-18 16:51
Yay!  Ok, the queue has cleared by itself now after the first task was cancel.  Thank you!!!

![whatsgoingon3](https://cloud.githubusercontent.com/assets/20520869/16923011/178c59c4-4ce6-11e6-8a04-bc4473b650e3.png)

**Comment by OurWebTeam** [comment] 2016-07-18 16:52
Yay! Ok, the queue has cleared by itself now after the first task was cancel. Thank you!!!

**Comment by timwood** [comment] 2016-09-08 13:27
I have run into what appears to be the same or similar issue, but I'm not seeing a cancel button on the view screen for a task.

**Comment by jonpugh** [comment] 2016-09-08 14:55
Thanks for your reports, all.

This one is tough to track down, because it seems to work fine when launching in Vagrant.

I am going to fire up a new server online to see if I can reproduce.

I will also add to the Troubleshooting docs page more information about how the Aegir Task Queue works.

@timwood Check the table 'semaphore' in the Drupal devmaster database.  If there is an entry for hosting_task, (the only entry), then delete it.

I'm not sure why you are not seeing the Cancel task, but another Aegir hack is to manually delete the task node.  Visit /node/#/delete for the task node you are looking at.  You can then just re-run a verify task.

**Comment by jonpugh** [comment] 2016-09-08 15:02
Spoke with @timwood in chat, his issue is separate, supervisor is not setup at all!

https://gitter.im/opendevshop/devshop?at=57d17c79cdbf820f7fa8f2c3

**Comment by jonpugh** [comment] 2016-09-08 15:20
I just installed a fresh copy of 1.0.0-beta10 at http://debug.devshop.systems/ and all tasks completed, unattended.

Closing this issue. @OurWebTeam feel free to re-open if you see it again.

@timwood check the playbook for supervisor here: https://github.com/opendevshop/ansible-role-devmaster/blob/master/tasks/supervisor.yml and the templates at https://github.com/opendevshop/ansible-role-devmaster/tree/master/templates

**Closed by jonpugh** 2016-09-08 15:20 UTC
