### ISSUE TITLE
Installation skips user creation causing playbook to fail.

### ISSUE THREAD

**Issue by arosboro** [opendevshop/devshop#100] opened 2016-04-26 15:27 UTC
commit opendevshop/ansible-role-aegir-user@b0c613be6d79d940c6e04436926215da3ad9fec4 isn't picking up the defined variable in https://github.com/opendevshop/ansible-role-aegir-user/blob/master/defaults/main.yml#

This can be seen at https://travis-ci.org/opendevshop/devmaster/jobs/125831318:

```
TASK [aegir.user : Create Aegir user] ******************************************
skipping: [devshop.travis]
```

**Comment by halofx** [comment] 2016-04-28 01:56
I think this is the same issue I am seeing. 

```
The error appears to have been in '/usr/share/devshop/roles/aegir.user/tasks/main.yml': line 14, column 37, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Create Aegir user
    when: "{{ aegir_create_user }}" == "yes"
                                    ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

**Comment by jonpugh** [comment] 2016-04-28 02:06
Sorry, @halofx I accidentally committed that to master.

I need to start locking in the ansible role versions.

Update the ansible Galaxy role and try again?

I'm starting to think that we need to do our own role management. Updating roles with Ansible Galaxy is not easy.

**Comment by halofx** [comment] 2016-04-28 03:04
I rolled back my VM to right before I downloaded the script. I pulled back down the beta1 install script and ran it again. This time I got a different error, but it seems to be pointing in the same direction.

At the same point, right after checking Composer, the Ansible playbook does seem to start.

For what it is worth, the problem is identical on Ubuntu 14.04, and 16.04.

```---------------------------------------------
 Installing with Ansible...
---------------------------------------------

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [devshop.halo.fx]

TASK [aegir.user : Include OS-specific variables.] *****************************
ok: [devshop.halo.fx]

TASK [aegir.user : Create Aegir Group (so we can set the GID)] *****************
changed: [devshop.halo.fx]

TASK [aegir.user : Create Aegir user] ******************************************
skipping: [devshop.halo.fx]

TASK [aegir.user : Ensure /var/aegir is owned by aegir user.] ******************
fatal: [devshop.halo.fx]: FAILED! => {"changed": false, "failed": true, "gid": 0, 
"group": "root", "mode": "0755", "msg": "chown failed: failed to look up user aegir",
"owner": "root", "path": "/var/aegir", "size": 4096, "state": "directory", "uid": 0}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @playbook.retry

PLAY RECAP *********************************************************************
devshop.halo.fx            : ok=3    changed=1    unreachable=0    failed=1

No passwd entry for user 'aegir'
The command 'devshop status' had an error. Check the logs and try again.
```

**Comment by jonpugh** [comment] 2016-04-28 14:01
Thanks for the details, @halofx I'm looking into this now

**Comment by jonpugh** [comment] 2016-04-28 15:00
@halofx @arosboro I fixed this and a few other missing things from the Apache role.

Please give it a shot!

**Comment by halofx** [comment] 2016-04-28 18:48
Well, I got further... Looks like a mysql issue now.

```

TASK [geerlingguy.mysql : Copy .my.cnf file with root password credentials.] ***
changed: [devshop.halo.fx]

TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.] ***********
fatal: [devshop.halo.fx]: FAILED! => {"changed": false, "cmd": ["mysql", "-NBe",
"SELECT Host FROM mysql.user WHERE User = \"\""], "delta": "0:00:00.004171",
"end": "2016-04-28 13:42:17.447204", "failed": true, "rc": 1, "start": "2016-04-28 13:42:17.443033",
"stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)",
"stdout": "", "stdout_lines": [], "warnings": []}

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************

RUNNING HANDLER [geerlingguy.mysql : restart mysql] ****************************
        to retry, use: --limit @playbook.retry

PLAY RECAP *********************************************************************
devshop.halo.fx            : ok=82   changed=33   unreachable=0    failed=1

-su: devshop: command not found
The command 'devshop status' had an error. Check the logs and try again.
```

**Comment by jonpugh** [comment] 2016-04-28 21:27
@halofx not sure, but it might have been fixed in the PR @geerlingguy just merged: https://github.com/geerlingguy/ansible-role-mysql/pull/115

The 1.x tests are passing.

I'm wondering if it's because you are running install.sh more than once... Maybe we should add a second run of install.sh to test idempotence

**Comment by halofx** [comment] 2016-04-29 00:23
I have been rolling back the VM to a snapshot I took right before downloading the script. So I am using a fresh script and system on each attempt.

This last attempt on Ubuntu 14.04 worked! Thanks!

**Comment by jonpugh** [comment] 2016-04-29 01:55
Ok, great! Since the tests are passing and @halofx reports it's working, I'm closing this issue.

**Closed** 2017-07-18 15:15 UTC
