### ISSUE TITLE
Drupal 8 development with composer

### ISSUE THREAD

**Issue by lsolesen** [opendevshop/devshop#117] opened 2016-05-16 13:31 UTC
In a typical d8 dev the index.php is inside a web directory. How does this fit into devshop? Should one build the web dir and put it into a git repos?

**Comment by jonpugh** [comment] 2016-05-16 14:42
@lsolesen DevShop Project's have a field for "Path to Drupal".

If you fill in this field with "web" or "docroot" or wherever your public files are, devshop will be able to install it.

![screen shot 2016-05-16 at 10 41 34 am](https://cloud.githubusercontent.com/assets/106420/15292804/e7d05542-1b52-11e6-94f2-15f6bc4a89b2.png)

**Comment by lsolesen** [comment] 2016-05-17 20:03
@jonpugh However, if I wanted to build off e.g. https://github.com/drupalcommerce/project-base the same issue as D7 site with make files applies. I need to build the project to a git-repos and commit it all, right?

**Comment by jonpugh** [comment] 2016-05-19 11:56
@lsolesen Yes, that's right. You need a full drupal codebase in the git repo for use with devshop.

**Comment by madalinignisca** [comment] 2016-06-03 20:17
I've started using the Drupal Composer skeleton for Drupal 8 and have similar issues. On local, if I try to use the global installed "drupal" console command, it fails with similar errors like on the "server".

But if I run the "drupal" console from `../vendor/bin/drupal` I can install and do whatever I need.

The problem is with the "drupal" console and libraries installed in the current project, so it would be best if the project's "drupal" console could be triggered for anything that is needed.

I encountered this problem with global installed "drupal" console even on other projects at work.

**Comment by drurian** [comment] 2016-08-25 00:22
Anyone had any luck with using drupal composer from https://github.com/drupal-composer/drupal-project? I've been running into some errors even thought I've committed the full D8 docroot in /web.

**Comment by madalinignisca** [comment] 2016-09-01 14:14
@drurian I had issues with it so I started my own skeleton. Anyway, the repos are deprecated and we all will be using the official ones. Check my [skeleton](https://packagist.org/packages/madalinignisca/drupal-skeleton) and let me know if you have issues.

I strongly suggest you start your own project skeleton suited to your needs.

**Comment by drurian** [comment] 2016-09-23 21:36
Thank you @madalinignisca It works for me. Have you used 8.2 yet?

**Comment by madalinignisca** [comment] 2016-09-25 06:31
Hi. Tested and yes. It's not such a complex thing what's in it. The skeleton is just a starting point done identically how any possible project skeleton is made for Composer. The drupal/core is the main package around we do our starting point and just keep growing from there. The current drupal/drupal package is totally unusable yet. It would require another package to provide the splitting parts of it, so it won't overwrite any customizations to certain files we're interested in.

**Comment by jonpugh** [comment] 2017-07-18 15:26
I need to test if it still works, but we do have a "Run  composer install if composer.json is found" feature.

Let's add some automated tests to confirm this.

**Comment by jonpugh** [comment] 2018-02-21 21:37
Provision now includes a `composer install` run if composer.json is present. Git integration has been fixed so a git repo project that needs a composer install will now work.

Thanks!

**Closed by jonpugh** 2018-02-21 21:37 UTC
Labels: Needs Tests
