### ISSUE TITLE
Cannot ensure PHP Packages on Digital Ocean Ubuntu 14.04

### ISSUE THREAD

**Issue by lsolesen** [opendevshop/devshop#109] opened 2016-05-12 11:51 UTC
```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************                     
failed: [devshop.intraface.dk] (item=[u'php7.0-common', u'php7.0-cli', u'php7.0-dev', u'php7.0-fpm', 
u'libpcre3-dev', u'php7.0-gd', u'php7.0-curl', u'php7.0-imap', u'php7.0-json', u'php7.0-opcache', u'p
hp7.0-xml', u'php7.0-mbstring', u'php7.0-apcu']) => {"failed": true, "item": ["php7.0-common", "php7.
0-cli", "php7.0-dev", "php7.0-fpm", "libpcre3-dev", "php7.0-gd", "php7.0-curl", "php7.0-imap", "php7.
0-json", "php7.0-opcache", "php7.0-xml", "php7.0-mbstring", "php7.0-apcu"], "msg": "No package matchi
ng 'php7.0-common' is available"}  
```

**Comment by jonpugh** [comment] 2016-05-13 19:19
Thanks, @lsolesen... this should be fixed in #110.

Give it a shot and let me know? 

Thanks!

**Comment by lsolesen** [comment] 2016-05-14 18:55
SamStill same problem after redownloading install.sh and running it. I cannot reopen this issue. Do you want me to create a new one @jonpugh?

**Comment by jonpugh** [comment] 2016-05-14 19:07
@lsolesen I think you might just need to update /usr/share/devshop

You can do that with either `sudo devshop self-update` (enter 1.x for version) or `cd /usr/share/devshop` and `git pull`

**Comment by lsolesen** [comment] 2016-05-14 19:58
@jonpugh That worked. When running `devshop status` everything has a green light. However, Nothing is found when navigating to my devshop.my-domain.dk. I've checked that the IP matches the box on DO.

**Comment by lsolesen** [comment] 2016-05-14 19:59
Installed using: 

    bash install.sh --hostname=devshop.my-domain.dk 

Just get a 404.

**Comment by jonpugh** [comment] 2016-05-14 20:10
Hmmm... Check the URL for the @hostmaster alias. If it was installed using a different URI, you might want to reinstall...

`rm -rf /var/aegir/devmaster-1.x
rm -rf /var/aegir/.drush/postmaster.alias.drushrc.php
bash install.sh --hostname=x.y.com`

**Comment by nhepner1** [comment] 2016-05-17 00:50
Also experiencing this issue during install on Linode against a fresh Ubuntu 14.04LTS instance. It is caused by a missing package for 'php7.0-common'.

I resolved this by adding the PPA for 'php7.0-common' as described here: https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04

```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
```

Perhaps this should be rolled into an Ansible role for installation to check for the package and add the repository PPA if not present?

**Comment by nhepner1** [comment] 2016-05-17 01:02
I should also point out that this did not resolve the 404 issue - seems like a different problem

**Comment by jonpugh** [comment] 2017-07-18 15:19
@geerlingguy's PHP role uses php7 for all 3.x versions of the role.

We've locked our roles.yml file to use 2.x only: https://github.com/opendevshop/devshop/blob/1.x/roles.yml

**Closed by jonpugh** 2017-07-18 15:19 UTC
