### ISSUE TITLE
Git Feature branches with slashes don't work

### ISSUE THREAD

**Issue by timwood** [opendevshop/devshop#140] opened 2016-07-22 18:15 UTC
When you try to switch an environment to a git branch which has a slash (/) in the path, it fails as it gets confused. Here is a screenshot of the logs:

![image](https://cloud.githubusercontent.com/assets/91050/17066826/c8c7f0b2-5016-11e6-8165-356ed5d14ff6.png)

**Comment by llwp** [comment] 2016-09-27 04:07
confirmed - seeing this consistently as well..

**Comment by arttus** [comment] 2016-10-24 19:51
Yep, it seems to be an issue. Git flow relies on organizing the repo this way, so it would be good to get this fixed.

I'm not a devshop developer but if someone can point me in the right direction I can commit some resources to it.

**Comment by jonpugh** [comment] 2016-10-26 17:28
@arttus https://github.com/opendevshop/devmaster/blob/1.x/modules/devshop/devshop_projects/drush/deploy.devshop.provision.inc#L58

I'm tracking this down now.

**Comment by jonpugh** [comment] 2016-10-26 17:31
So with aegir, every task is a drush command... in the case of `provision-devshop-deploy` command, "git_ref" is an argument...

This might be a problem with drush.  Can a slash exist in a drush argument?  We might have to switch git_ref to be a drush option instead.

**Comment by jonpugh** [comment] 2016-10-26 17:54
Nope I am wrong, I just wasn't parsing the git refs properly.  Commit comming shortly.

**Comment by arttus** [comment] 2016-10-26 17:58
Awesome news jon, thanks for the quick response, I will update and close the issue over on D.O.

**Comment by jonpugh** [comment] 2016-10-26 17:59
Ok, that's it. I finally cleaned up getBranchesAndTags().  
![screenshot from 2016-10-26 13-58-47](https://cloud.githubusercontent.com/assets/106420/19738191/7728ed60-9b84-11e6-8814-a51b5122e714.png)

**Closed** 2017-07-07 20:12 UTC
