### ISSUE TITLE
following latest 1.x branch code upgrades ?

### ISSUE THREAD

**Issue by gregoryo** [opendevshop/devshop#161] opened 2016-11-06 15:03 UTC
hi Jon, thanks for this project.
didn't see docs on following latest code.
do you have a recommended process for this?
should i just git pull on top of the existing installs to /var/aegir/devmaster-1.x/

initially, 2 weeks ago, did a git pull and ran install from 1.x branch HEAD
now want to get the fix for #140 
run 
```
devshop upgrade '1.x'
```
failed on the STEP 1: Upgrade DevMaster showing a couple of errors - so this may be a duplicate or related to #159 
```
Changed permissions of                                               [success]
/var/aegir/devmaster-1.x/sites/all/drush/drushrc.php to 644
Generated config in write(): Platform Drush configuration file       [success]
(/var/aegir/devmaster-1.x/sites/all/drush/drushrc.php)
Changed permissions of                                               [success]
/var/aegir/devmaster-1.x/sites/all/drush/drushrc.php to 444
Platforms path /var/aegir/platforms exists.                          [success]
Platforms ownership of /var/aegir/platforms has been changed to      [success]
aegir.
Platforms permissions of /var/aegir/platforms have been changed to   [success]
755.
Platforms path /var/aegir/platforms is writable.                     [success]
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
This task is not valid                                               [error]
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
This task is not valid                                               [error]
Changed permissions of /var/aegir/.drush/hostmaster.alias.drushrc.php[success]
to 640
Generated config in write(): Drush configuration file                [success]
(/var/aegir/.drush/hostmaster.alias.drushrc.php)
... 
subsequent commands all appeared to work
```
even with the "upgrade failed" message, i have
/var/aegir/devmaster-1.x and
/var/aegir/devmaster-1.x-2016-11-06 directories.

**Comment by jonpugh** [comment] 2016-11-08 13:33
Hey @gregoryo...

I'm still digging to figure out why that error is occuring "This task is not valid", see #159.

In the mean time, yes, you can manually git pull the 1.x branch of the repo at /var/aegir/devmaster-1.x/profiles/devmaster.

I'll update this issue once the other one is fixed.

**Comment by jonpugh** [comment] 2016-11-08 16:46
Closing as a duplicate of #159

**Closed by jonpugh** 2016-11-08 16:46 UTC
