### ISSUE TITLE
"Path" in branch name is not recognised

### ISSUE THREAD

**Issue by loziju** [opendevshop/devshop#42] opened 2016-01-21 08:26 UTC
devshop version: 0.5.4

In github, I created branch with "path" in the name, e.g. `features/new-theme`. Please refer to the screenshot below. Please also note that there is another branch named `new-theme` which will be explained below.

![](http://files.po.sg/142j0u013N1M/Google%20Chrome%20-%20github.com%20-%20Branches%20%C2%B7%20pixelonion-smuedusg%20-%20Screen%20Shot%2021%20Jan%202016%204.00.24%20pm.png)

In devshop, branch with "path" only shows the last component of the path, e.g. `features/new-theme` is shown as _new-theme_, `features/foo/bar` is shown as _bar_. When creating a new environment and selecting _bar_, `master` branch is the one being deployed to the new environment.

![](http://files.po.sg/3Y2s0D301C15/Google%20Chrome%20-%20devshop.po.sg%20-%20smu%20-%20DevShop%20-%20Screen%20Shot%2021%20Jan%202016%203.59.56%20pm.png)

The screenshot above was done after another branch: `new-theme` was created. This is to circumvent the issue of devshop not detecting `features/new-theme`.

**Comment by jonpugh** [comment] 2016-01-21 13:07
Hi @loziju, thanks for reporting this.  

The problem is in the function getBranchesAndTags():  https://github.com/opendevshop/devmaster/blob/0.x/modules/devshop/devshop_projects/drush/contexts.inc#L65

I am not great at regex and processing so it's just a bunch of "explode()" calls.

We should probably look into using GitWrapper for this, it's likely they figured out how to get a list of branches and tags in a much more reliable way.

**Comment by jonpugh** [comment] 2017-07-18 14:15
Thanks @loziju, this was fixed in commit https://github.com/opendevshop/devmaster/commit/389019a9b4314d50bbc04683abaace25f3a5d0ba

**Closed by jonpugh** 2017-07-18 14:15 UTC
Labels: bug
