### ISSUE TITLE
Should Opcache be enabled by default?

### ISSUE THREAD

**Issue by madalinignisca** [opendevshop/devshop#129] opened 2016-06-08 19:03 UTC
I think that Opcache should be enabled by default.

The Ansible book for PHP requires to have `php_opcache_enabled_in_ini` set to true.

Also, there are some additional variables that would help fine tuning PHP and others for some extra performance.

**Comment by jonpugh** [comment] 2017-07-18 19:19
I agree. I want to better leverage the Ansible inventory file for this. Right now the install.sh script creates an ansible inventory file right next to the installer, but we might as well use the system inventory file.

Then we can document how to use that to edit ansible variables and inventory.

Can you list the other tweaks you would make?

**Comment by jonpugh** [comment] 2018-02-21 21:44
Closing as duplicate of #199

**Closed by jonpugh** 2018-02-21 21:44 UTC
Labels: improvement
