### ISSUE TITLE
PDOException prevents upgrade,  General error: 1366 Incorrect integer value

### ISSUE THREAD

**Issue by adrinux** [opendevshop/devshop#175] opened 2016-12-19 15:42 UTC
Just ran a devshop upgrade of 1.x and snagged this error which causes the upgrade to fail:
```
WD node: PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect[error]
integer value: 'HOSTING_ADMIN_CLIENT' for column 'gid' at row 2:
```
Here's the relevant section from the devshop upgrade output:
```
Generated config in write(): virtual host configuration file         [success]
(/var/aegir/config/server_master/nginx/vhost.d/ods.perlucida.uk)
4 byte UTF-8 for mysql is disabled. See the documentation on adding 4[warning]
byte UTF-8 support for more information. (Currently using Database 4
byte UTF-8 support Disabled)
 Devshop_github    7001  Set a weight higher than devshop_project module.
 Devshop_projects  7004  Enable Hosting Git and Hosting Git Checkout.
 Devshop_projects  7005  Save git_ref data to hosting_git table and drop the
                         devshop environment's git_ref field.
 Devshop_projects  7007  Reduce the character limit for bootstrap to turn form
                         element descriptions into tooltips.
 Devshop_projects  7008  Set weight of devshop_projects module to 1 so it loads
                         alters after hosting_git.
 Devshop_testing   7000  Set a weight higher than devshop_project so our form
                         altering can access the project settings.
Do you wish to run all pending updates? (y/n): y
4 byte UTF-8 for mysql is disabled. See the documentation on adding 4[warning]
byte UTF-8 support for more information. (Currently using Database 4
byte UTF-8 support Disabled)
WD node: PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect[error]
integer value: 'HOSTING_ADMIN_CLIENT' for column 'gid' at row 2:
INSERT INTO {node_access} (nid, realm, gid, grant_view, grant_update,
grant_delete) VALUES (:db_insert_placeholder_0,
:db_insert_placeholder_1, :db_insert_placeholder_2,
:db_insert_placeholder_3, :db_insert_placeholder_4,
:db_insert_placeholder_5), (:db_insert_placeholder_6,
:db_insert_placeholder_7, :db_insert_placeholder_8,
:db_insert_placeholder_9, :db_insert_placeholder_10,
:db_insert_placeholder_11); Array
(
    [:db_insert_placeholder_0] => 376
    [:db_insert_placeholder_1] => hosting task
    [:db_insert_placeholder_2] => 1
    [:db_insert_placeholder_3] => 1
    [:db_insert_placeholder_4] => 0
    [:db_insert_placeholder_5] => 0
    [:db_insert_placeholder_6] => 376
    [:db_insert_placeholder_7] => hosting task
    [:db_insert_placeholder_8] => HOSTING_ADMIN_CLIENT
    [:db_insert_placeholder_9] => 1
    [:db_insert_placeholder_10] => 0
    [:db_insert_placeholder_11] => 0
)
 in node_access_write_grants() (line 3566 of
/var/aegir/devmaster-1.x-2016-12-19-1/modules/node/node.module).
SQLSTATE[HY000]: General error: 1366 Incorrect integer value:        [error]
'HOSTING_ADMIN_CLIENT' for column 'gid' at row 2
Performed update: devshop_projects_update_7004                       [ok]
Performed update: devshop_testing_update_7000                        [ok]
Performed update: devshop_github_update_7001                         [ok]
'all' cache was cleared.                                             [success]
Finished performing updates.                                         [ok]
```

(There's a note about this error in Koumbit's [Aegir wiki](https://wiki.koumbit.net/AegirConfiguration) (under headings 'Problems', 'PDOException during updb in node_access table') which says "This doesn't seem to cause any outward issues and can more or less be ignored. The node_access table can be rebuilt later". But nothing I can find in the Aegir issue queue.)

**Comment by jonpugh** [comment] 2016-12-19 15:44
The issue is this:

> Incorrect integer value: 'HOSTING_ADMIN_CLIENT' for column 'gid' at row 2:

If the constant HOSTING_ADMIN_CLIENT is not set, it's passed as a string to the query...

Not sure how to fix this. We should look for where that constant is set.

**Comment by adrinux** [comment] 2016-12-20 14:43
Ah. I need to take a closer look, if this is only affecting me it may just be that a site doesn't have HOSTING_ADMIN_CLIENT set – specifically thinking of the site I was experimenting importing with provision-deploy.  I was passing --client_name but maybe that hasn't stuck...

**Comment by adrinux** [comment] 2016-12-20 18:31
It's set in devmaster_bootstrap() in devmaster.profile. But this is error is occurring during the db update when it tries to add a new row. I can't figure out which update runs that though. Where is the 'Devshop_testing   7000' update defined?

There is this little snippet in devshop_projects.install, commented out, but relevant?
```
// @TODO: This breaks upgrades. Figure out why and in include it in an upcoming release.
///**
// * Enable devshop_testing.
// */
//function devshop_projects_update_7002 () {
//  module_enable(array(
//    'devshop_testing',
//  ));
//}
```

**Comment by jonpugh** [comment] 2017-04-21 17:25
@adrinux This was fixed in the commit listed above. Upgrade testing is back, and is passing. You should be able to upgrade to 1.x now.

Thanks!

**Closed by jonpugh** 2017-04-21 17:25 UTC
